spring:
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?characterEncoding=utf-8
    username: root
    password: "0121"
    poolPreparedStatements: false
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 10000
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: wall

  #数据库操作语句
  jpa:
    database: MySQL
    show-sql: true

  #HTML模板引擎,用于跳转到.HTML页面
  thymeleaf:
    prefix: classpath:/templates/HTML/
    suffix: .html
    mode: LEGACYHTML5
    cache: false

  #静态资源
  mvc:
    static-path-pattern: /**

  #上传文件大小
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 2048Mb

  #配置kafka
  kafka:
    #主机IP
    bootstrap-servers: 192.168.123.16:9092
    consumer:
      enable:
        auto:
          commit: true
      session:
        timeout: 6000
      auto:
        commit:
          interval: 100
        offset:
          reset: latest
      group-id: springboot-group
      concurrency: 10
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      servers: 192.168.123.16:9092
      retries: 1
      batch:
        size: 4096
      linger: 1
      buffer:
        memory: 40960